title: fatdev.ninja
email: jeffhann@gmail.com
description: Welcome to DevOps, I'll be your guide, the Fat Dev Ninja
baseurl: ""
url: "https://fatdev.ninja"
twitter_username: obihann
github_username:  obihann
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
